config/routes.rb
AmberlockDemo::Application.routes.draw do

  resources :artists

  devise_for :users, controllers: { sessions: 'sessions', registrations: 'registrations' } do
    root to: 'sessions#new'
  end

  resources :users do
    collection do
      get :amberlock
      get :request_unlock
      post :verify_unlock
    end
    member do
      get :enable
      post :add_mobile
    end
  end

  match '/amberlocked', to: 'users#amberlock', as: :amberlocked

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  attr_accessible :band, :bio, :genre, :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :mobile, :enabled
  # attr_accessible :title, :body
  #
  # after_save :subscribe_user

  def subscribe!(mobile_no)
    amberlock = Amberlock::Amber.new('rPLqG41JuX2k8hC2woZq','DA-54ad0e02e5df')
    self.enabled = true
    self.mobile = mobile_no
    self.save!
    amberlock.subscribe_user(mobile, email)
  end

end

app/controllers/amberlock_controller.rb
class AmberlockController < ApplicationController
  def enable_user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


  def check_blocked?
    if session[:blocked].eql? true
      redirect_to amberlocked_path
    end
  end

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_filter :check_blocked?
  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @artists }
    end
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    @artist = Artist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @artist }
    end
  end

  # GET /artists/new
  # GET /artists/new.json
  def new
    @artist = Artist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @artist }
    end
  end

  # GET /artists/1/edit
  def edit
    @artist = Artist.find(params[:id])
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(params[:artist])

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render json: @artist, status: :created, location: @artist }
      else
        format.html { render action: "new" }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /artists/1
  # PUT /artists/1.json
  def update
    @artist = Artist.find(params[:id])

    respond_to do |format|
      if @artist.update_attributes(params[:artist])
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy

    respond_to do |format|
      format.html { redirect_to artists_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def landing
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    artists_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  protected

  AMBERLOCK = Amberlock::Amber.new('rPLqG41JuX2k8hC2woZq','DA-54ad0e02e5df')

  def after_sign_in_path_for(resource)
    if current_user.enabled.eql? true
      session[:blocked] = true
      session[:user_id] = current_user.id
      amberlocked_path
    else
      artists_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_filter :verify_authenticity_token
  before_filter :check_blocked?, only: :show

  AMBERLOCK = Amberlock::Amber.new('rPLqG41JuX2k8hC2woZq','DA-54ad0e02e5df')

  def show
    @user = User.find params[:id]
  end

  def enable
    @user = User.find params[:id]
    AMBERLOCK.subscribe_user(@user.mobile, @user.email)
  end

  def request_unlock
    @user = User.where(id: session["warden.user.user.key"][0]).first
    raw_response = AMBERLOCK.request_unlock(@user.mobile, @user.email)
    parsed = JSON.parse(raw_response)
    session[:unlock_code] = parsed["amber_code"]["value"]
    redirect_to amberlocked_path
  end

  def verify_unlock
    if params[:unlock_code] == session[:unlock_code]
      session[:blocked] = false
      redirect_to artists_path
    else
      render json: { status: 'failed', message: 'incorrect unlock code'}
    end
  end

  def edit
    @user = User.find params[:id]
  end

  def add_mobile
    @user = User.find params[:id]
    @user.subscribe!(params[:mobile])
    redirect_to artists_path
  end

  def update
    @user = User.find params[:id]
    if @user.update_attributes(params[:user])
      redirect_to artists_path
    else
      render 'edit'
    end
  end

end

app/helpers/amberlock_helper.rb
module AmberlockHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def enable_or_not
    case current_user.enabled
    when true
      "Enabled"
    when false
      "Disabled"
    end
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/amberlock/enable_user.html.haml
%h1 Amberlock#enable_user
%p Find me in app/views/amberlock/enable_user.html.haml

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :band %><br />
    <%= f.text_field :band %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_field :bio %>
  </div>
  <div class="field">
    <%= f.label :genre %><br />
    <%= f.text_field :genre %>
  </div>
  <div class="actions">
    <%= f.submit "Create!", class: "btn btn-success"%>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<h1> Welcome <%= "#{current_user.email}" %><h1>
<hr>

<h1>Listing artists</h1>

<table class='table table-striped table-bordered table-condensed'>
  <tr>
    <th>Name</th>
    <th>Band</th>
    <th>Bio</th>
    <th>Genre</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @artists.each do |artist| %>
  <tr>
    <td><%= artist.name %></td>
    <td><%= artist.band %></td>
    <td><%= artist.bio %></td>
    <td><%= artist.genre %></td>
    <td><%= link_to 'Show', artist %></td>
    <td><%= link_to 'Edit', edit_artist_path(artist) %></td>
    <td><%= link_to 'Destroy', artist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Artist', new_artist_path, class: "btn"%>

app/views/artists/new.html.erb
<h1>New artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @artist.name %>
</p>

<p>
  <b>Band:</b>
  <%= @artist.band %>
</p>

<p>
  <b>Bio:</b>
  <%= @artist.bio %>
</p>

<p>
  <b>Genre:</b>
  <%= @artist.genre %>
</p>


<%= link_to 'Edit', edit_artist_path(@artist) %> |
<%= link_to 'Back', artists_path %>

app/views/layouts/_header.html.erb
<h6>
  <img src="http://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50" />
  <h3> <%= "Email: #{current_user.email}"%> </h3>
  <hr>
  <h5> Want more secured account?  | <span class="label label-warning"><%= "#{enable_or_not}" %></span> </h5>
  <%= link_to 'Click me to enable Two-Factor Authentication', edit_user_path(@user), class: "btn" %>
</h6>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AmberlockDemo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class='container'>
  <% if user_signed_in? %>
    <h6><%= link_to 'Manange Profile', user_path(current_user.id) %>
    <h6><%= link_to 'Artists', artists_path %>
    <h6><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
  <% end %>
  <hr>
  <%= yield %>
</div>

</body>
</html>

app/views/users/_form.html.erb
<%= form_tag add_mobile_user_path(@user) do %>
  <%= "Mobile Number:"%>
  <%= text_field_tag :mobile %>
  <%= submit_tag 'Add my mobile', class: "btn btn-success" %>
<% end %>

app/views/users/amberlock.html.erb
<h1> Stop! Please unlock the AmberLock </h1>
<%= link_to request_unlock_users_path, confirm: 'This will send a amberlock code' do %>
  <%= 'Generate Unlock Code' %>
<% end %>

<%= form_tag verify_unlock_users_path do %>
  <%= text_field_tag "unlock_code" %>
  <%= submit_tag 'Sign me in', class: "btn btn-success"%>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', user_path(@user) %>

app/views/users/show.html.erb
<h3> Manage your Profile </h3>
<%= render 'layouts/header' %>